### ISSUE TITLE
Allow uploading docs to a separate repo

### ISSUE THREAD

**Issue by asmeurer** [gforsyth/doctr#12]
This is what we do with SymPy, for instance. It should be an easy modification to make.

**Comment by asmeurer** [comment]
I guess this should already work. You just need to pass whatever repo you want to push to to the `setup_GitHub_push(repo)` function, and it will add the remote for that repo, and use its gh-pages. It doesn't have to be the same repo that you started with (git is very lax about that sort of thing; you can add remotes for completely different repos all to the same cloned repository).

So we just need to make it configurable from the command line. At https://github.com/gforsyth/doctr/pull/23, I made it detect the repo automatically, but it will be easy to add a `--gh-pages-repo` flag to change it.

**Comment by gforsyth** [comment]
@asmeurer -- is the token that's generated per-user or per-repo?  Do we need to consider a second secret if someone pushes to a separate repo?

**Comment by asmeurer** [comment]
The tokens now are user-based. They grant access to `public_repo`, which means read/write access to *all* public repos for the authenticated user (which is why I'm worried about this and am hoping there's a more restrictive permission we can use).

**Comment by asmeurer** [comment]
Even if it were restrictive, there would only need to be one secret, for the repo that is being pushed to. Everything else is public. In particular, getting the Travis public key for a repo to encrypt the secret doesn't require any authentication. You could encrypt an environment variable for Travis builds for repo that you don't even control, if you wanted to.
