### ISSUE TITLE
Install doctr on Travis

### ISSUE THREAD

**Issue by gforsyth** [gforsyth/doctr#26]
We should be installing ourselves in the travis builds, no?

**Comment by asmeurer** [comment]
You mean to auto-edit the .travis.yml?

**Comment by gforsyth** [comment]
I mean that if someone is using `doctr`, they need to pip/conda install doctr in their .travis.yml so that the command is available

**Comment by asmeurer** [comment]
So it's just a docs update?

**Comment by gforsyth** [comment]
For now, yeah.

**Comment by asmeurer** [comment]
The docs now say this. Auto-editing would be cool, but it's much harder. We should open a separate issue for it if we want it.
